# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
      architecture: 'x64'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use python $(python.version)'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- script: |
    pip install --upgrade sphinx
    pip install sphinx_rtd_theme
  displayName: 'Install sphynx'

#- script: |
#    python setup.py install
#  displayName: 'setup python package'

- task: CmdLine@2
  inputs:
    script: 'make html'
    workingDirectory: '$(Build.SourcesDirectory)/docs'
  displayName: 'Compile documentation'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/docs/_build/html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
  displayName: 'Copy documentation files to artifact directory'

# FTP upload
# Upload files using FTP
- taks FtpUpload@2
  inputs:
    credentialsOption: inputs
    serverUrl: 40.79.79.150:21
    username: devops
    password: hU85T3rD0c5-Au7o&Bu1Ld
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    remoteDirectory: '/hubster-docs'
    trustSSL: true
    displayName: 'FTP upload'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#   ArtifactName: 'drop'
#    publishLocation: 'Container'
#  displayName: 'Publish documentation as artifact'
  
# pip install -r Requirements.txt removed from dependencies
